import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import AppHeader from "../components/layout/Header";
import AppFooter from "../components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tadaa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <div
            style={{
              minHeight: "100vh",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <AppHeader />
            <main
              style={{
                flex: 1,
                background: "var(--background)",
              }}
            >
              {children}
            </main>
            <AppFooter />
          </div>
          {/*          
          <App>
            <Layout style={{ minHeight: "100vh" }}>
              <AppHeader />

              <Content
                style={{
                  flex: 1,
                  background: "var(--background)",
                  position: "relative",
                }}
              >
                {children}
              </Content>

              <AppFooter />
            </Layout>
          </App> */}
        </AntdRegistry>
      </body>
    </html>
  );
}
