import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import MainWrapper from "@/components/layout/MainWrapper";
import { App, ConfigProvider } from "antd";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tadaa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#580e9f",
              borderRadius: 8,
              colorBgContainer: "white",
            },
            components: {
              Progress: {
                defaultColor: "var(--colorHighlightPrimary)",
                circleTextColor: "var(--colorTextSecondary)",
              },
            },
          }}
        >
          <AntdRegistry>
            <App>
              <MainWrapper>{children}</MainWrapper>
            </App>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
